import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  login: {
    flex: 1,
    borderColor: 'gray',
    borderWidth: 100,
  },
  setting: {
    flex: 1,
    backgroundColor: "#f5f5f8",
    justifyContent: 'center',
    alignItems: 'center',
  },
  news: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: 'center',
    alignItems: 'center',
  },
  hse: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: 'center',
    alignItems: 'center',
  },
  input: {
    borderRadius: 4,
    bottom: 50,
    top: -100,
    left: -137,
    width: 250,
    height: 40,
    margin: 12,
    borderWidth: 1,
    padding: 10,
  },
  login: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#f5f5f8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  login_container: {
    width: 300,
    height: 100,
    backgroundColor: '#fff',
    paddingHorizontal: 150,
    paddingVertical: 150,
    borderRadius: 10,
  },
  button: {
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 4,
    backgroundColor: '#007aff',
    width: 200,
    bottom: 50,
    left: 50,
    position: 'absolute',
  },
  deconnect: {
    paddingVertical: 12,
    borderColor: "#f5f5f8",
    borderWidth: 1,
    backgroundColor: 'white',
    width: 390,
    bottom: 300,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  text_disconnect: {
    paddingTop: 5,
    color: 'red',
    left: 10,
  },
  container_camera: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  button_goto_camera: {
    position: 'absolute',
    bottom: 20,
    alignSelf: 'center',
    backgroundColor: '#2196F3',
    borderRadius: 50,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  text_button_goto_camera: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  button_camera: {
    position: 'absolute',
    bottom: 20,
    alignSelf: 'center',
    width: 102,
    height: 102,
    borderRadius: 100,
    backgroundColor: 'black',
    alignItems: 'center',
    justifyContent: 'center',
  },
  button_camera_round: {
    width: 90,
    height: 90,
    borderRadius: 100,
    backgroundColor: '#fff',
  },
  button_risk: {
    position: 'absolute',
    bottom: 20,
    backgroundColor: '#E74C3C',
    borderRadius: 100,
    paddingTop: 23,
    width: 100,
    height: 100,
  },
  text_button_risk: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    justifyContent: 'center',
    textAlign: 'center',
  },
  input_risk: {
    borderRadius: 4,
    width: 360,
    alignSelf: 'center',
    height: 250,
    margin: 12,
    borderWidth: 1,
    padding: 10,
  },
  container1: {
    flex: 1,
    backgroundColor: '#F5F5F5',
    paddingHorizontal: 20,
    paddingTop: 30,
    paddingBottom: 10,
    borderColor: '#BFBFBF',
    borderWidth: 1,
    borderRadius: 10,
  },
  sectionHeader1: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 10,
    color: '#483D8B',
  },
  item1: {
    fontSize: 16,
    marginVertical: 5,
    marginLeft: 20,
    color: '#696969',
  },
});